// GENERATED by scripts/gen-subgraph-config.mjs — do not edit by hand.
// Source: deployments\arc-testnet.json (network arc-testnet, chainId 5042002)

import { Address } from "@graphprotocol/graph-ts";

export const TICKET_NFT = Address.fromString("0xb2490568bb27c9c38588e3b5511ee3980892cce4");
export const ESCROW = Address.fromString("0x07ab57380db7df630fab2d3d3a1019a5a890b018");
export const INTENT_REGISTRY = Address.fromString("0x479b4455f494679dcdd6f6f32e93e08682deda75");
export const SETTLEMENT = Address.fromString("0x75872168f2d6ae13c7d9258159e59025fd9b5eae");
export const USDC = Address.fromString("0x3600000000000000000000000000000000000000");

export const CHAIN_ID = 5042002;
